apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
{{KUSTOMIZE_RESOURCES}}

commonLabels:
  app.kubernetes.io/name: {{SERVICE_NAME}}
  app.kubernetes.io/instance: {{SERVICE_NAME}}-{{ENVIRONMENT}}
  app.kubernetes.io/managed-by: devlift
  devlift.ai/tenant: {{TENANT_CODE}}
  devlift.ai/environment: {{ENVIRONMENT}}

namespace: {{NAMESPACE}}
