apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{SERVICE_NAME}}-secrets-csi
  namespace: {{NAMESPACE}}
spec:
  provider: aws
  parameters:
    region: "{{AWS_REGION}}"
    objects: |
      - objectName: "{{SECRETS_MANAGER_PATH}}"
        objectType: "secretsmanager"
        jmesPath:
{{SECRET_JMES_PATH_ITEMS}}
  secretObjects:
{{SECRET_OBJECTS}}
