apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{SERVICE_NAME}}-sa
  namespace: {{NAMESPACE}}
  annotations:
    eks.amazonaws.com/role-arn: {{SECRETS_ACCESS_ROLE_ARN}}
  labels:
    app: {{SERVICE_NAME}}
    app.kubernetes.io/name: {{SERVICE_NAME}}
    app.kubernetes.io/instance: {{SERVICE_NAME}}-{{ENVIRONMENT}}
    app.kubernetes.io/managed-by: devlift
