# Auto-generated from TypeScript mock data — do not edit manually.

FINTECH_DEMO = {
    "geoLocations": [
        {
            "id": "geo-dubai",
            "name": "Dubai",
            "displayName": "Dubai",
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {},
        },
        {
            "id": "geo-mumbai",
            "name": "Mumbai",
            "displayName": "Mumbai",
            "position": {
                "x": 700,
                "y": 0,
            },
            "settings": {},
        },
    ],
    "accounts": [
        {
            "id": "account-gcp-neoflow-prod",
            "accountId": "neoflow-gcp-prod",
            "vendor": "GCP",
            "geoLocationId": "geo-dubai",
            "position": {
                "x": 30,
                "y": 48,
            },
            "settings": {},
        },
        {
            "id": "account-aws-neoflow-prod",
            "accountId": "neoflow-aws-prod",
            "vendor": "AWS",
            "geoLocationId": "geo-mumbai",
            "position": {
                "x": 30,
                "y": 48,
            },
            "settings": {},
        },
    ],
    "cloudRegions": [
        {
            "id": "cr-gcp-me-central1",
            "name": "me-central1",
            "displayName": "me-central1 (Dubai)",
            "accountId": "account-gcp-neoflow-prod",
            "settings": {},
        },
        {
            "id": "cr-aws-ap-south-1-neoflow",
            "name": "ap-south-1",
            "displayName": "ap-south-1 (Mumbai)",
            "accountId": "account-aws-neoflow-prod",
            "settings": {},
        },
    ],
    "vpcs": [
        {
            "id": "vpc-neoflow-gcp-dubai",
            "name": "neoflow-prod-dubai-vpc",
            "cloudRegionId": "cr-gcp-me-central1",
            "cidr": "10.10.0.0/16",
            "settings": {},
        },
        {
            "id": "vpc-neoflow-aws-mumbai",
            "name": "neoflow-prod-mumbai-vpc",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "cidr": "10.20.0.0/16",
            "settings": {},
        },
    ],
    "subnets": [
        {
            "id": "subnet-neoflow-gcp-app-1a",
            "name": "neoflow-prod-dubai-app-subnet-1a",
            "type": "private",
            "cidr": "10.10.1.0/24",
            "vpcId": "vpc-neoflow-gcp-dubai",
            "displayOrder": 0,
        },
        {
            "id": "subnet-neoflow-gcp-data-1a",
            "name": "neoflow-prod-dubai-data-subnet-1a",
            "type": "private",
            "cidr": "10.10.2.0/24",
            "vpcId": "vpc-neoflow-gcp-dubai",
            "displayOrder": 1,
        },
        {
            "id": "subnet-neoflow-aws-app-1a",
            "name": "neoflow-prod-mumbai-app-subnet-1a",
            "az": "ap-south-1a",
            "type": "private",
            "cidr": "10.20.1.0/24",
            "vpcId": "vpc-neoflow-aws-mumbai",
            "displayOrder": 0,
        },
        {
            "id": "subnet-neoflow-aws-data-1a",
            "name": "neoflow-prod-mumbai-data-subnet-1a",
            "az": "ap-south-1b",
            "type": "private",
            "cidr": "10.20.2.0/24",
            "vpcId": "vpc-neoflow-aws-mumbai",
            "displayOrder": 1,
        },
    ],
    "nodes": [
        {
            "id": "gcp-dubai/payment-gateway-service",
            "name": "payment-gateway-service",
            "resourceType": "service",
            "status": "online",
            "statusText": "2/2 running",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": [
                "subnet-neoflow-gcp-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "resourceSubtype": "gke_service",
                "clusterName": "neoflow-prod-dubai-gke-cluster",
                "vpcId": "vpc-neoflow-gcp-dubai",
                "namespace": "neoflow",
                "runningCount": 2,
                "desiredCount": 2,
                "containers": [
                    {
                        "name": "payment-gateway",
                        "image": "gcr.io/neoflow-prod/payment-gateway:v2.4.1",
                    },
                ],
            },
        },
        {
            "id": "gcp-dubai/transaction-processor-service",
            "name": "transaction-processor-service",
            "resourceType": "service",
            "status": "online",
            "statusText": "2/2 running",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": [
                "subnet-neoflow-gcp-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "resourceSubtype": "gke_service",
                "clusterName": "neoflow-prod-dubai-gke-cluster",
                "vpcId": "vpc-neoflow-gcp-dubai",
                "namespace": "neoflow",
                "runningCount": 2,
                "desiredCount": 2,
                "containers": [
                    {
                        "name": "transaction-processor",
                        "image": "gcr.io/neoflow-prod/transaction-processor:v1.9.0",
                    },
                ],
            },
        },
        {
            "id": "gcp-dubai/kyc-verification-service",
            "name": "kyc-verification-service",
            "resourceType": "service",
            "status": "online",
            "statusText": "1/1 running",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": [
                "subnet-neoflow-gcp-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "resourceSubtype": "gke_service",
                "clusterName": "neoflow-prod-dubai-gke-cluster",
                "vpcId": "vpc-neoflow-gcp-dubai",
                "namespace": "neoflow",
                "runningCount": 1,
                "desiredCount": 1,
                "containers": [
                    {
                        "name": "kyc-verification",
                        "image": "gcr.io/neoflow-prod/kyc-verification:v3.1.2",
                    },
                ],
            },
        },
        {
            "id": "gke-node-dubai-001",
            "name": "gke-node-pool-neoflow-app-001",
            "resourceType": "service",
            "status": "online",
            "statusText": "Ready",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": [
                "subnet-neoflow-gcp-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "gke",
                "clusterName": "neoflow-prod-dubai-gke-cluster",
                "resourceSubtype": "gce",
                "instanceId": "gke-neoflow-prod-dubai-gke-cluster-node-001",
                "nodeGroupName": "node-pool-neoflow-app",
                "vpcId": "vpc-neoflow-gcp-dubai",
            },
        },
        {
            "id": "gke-ds-neoflow-prod-dubai-gke-cluster-neoflow-audit-agent",
            "name": "neoflow-audit-agent",
            "resourceType": "service",
            "status": "online",
            "statusText": "3/3 ready",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "gke",
                "clusterName": "neoflow-prod-dubai-gke-cluster",
                "vpcId": "vpc-neoflow-gcp-dubai",
                "resourceSubtype": "gke_daemonset",
                "namespace": "neoflow-system",
                "desiredNumberScheduled": 3,
                "numberReady": 3,
                "containers": [
                    {
                        "name": "neoflow-audit-agent",
                        "image": "gcr.io/neoflow-prod/audit-agent:v1.2.0",
                    },
                ],
            },
        },
        {
            "id": "gke-ds-neoflow-prod-dubai-gke-cluster-neoflow-secrets-agent",
            "name": "neoflow-secrets-agent",
            "resourceType": "service",
            "status": "online",
            "statusText": "3/3 ready",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "gke",
                "clusterName": "neoflow-prod-dubai-gke-cluster",
                "vpcId": "vpc-neoflow-gcp-dubai",
                "resourceSubtype": "gke_daemonset",
                "namespace": "neoflow-system",
                "desiredNumberScheduled": 3,
                "numberReady": 3,
                "containers": [
                    {
                        "name": "neoflow-secrets-agent",
                        "image": "gcr.io/neoflow-prod/secrets-agent:v2.0.1",
                    },
                ],
            },
        },
        {
            "id": "gcp-dubai/ledger-db",
            "name": "ledger-db",
            "resourceType": "database",
            "status": "online",
            "statusText": "Available",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": [
                "subnet-neoflow-gcp-data-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "databaseType": "cloud-sql-postgresql",
            },
        },
        {
            "id": "gcp-dubai/compliance-reports-store",
            "name": "compliance-reports-store",
            "resourceType": "bucket",
            "status": "online",
            "statusText": "Online",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {},
        },
        {
            "id": "gcp-dubai/payment-events-queue",
            "name": "payment-events-queue",
            "resourceType": "queue",
            "status": "online",
            "statusText": "Online",
            "vendor": "GCP",
            "cloudRegion": "me-central1",
            "cloudRegionId": "cr-gcp-me-central1",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {},
        },
        {
            "id": "neoflow-prod-eks-cluster/payment-gateway-service",
            "name": "payment-gateway-service",
            "resourceType": "service",
            "status": "online",
            "statusText": "2/2 running",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": [
                "subnet-neoflow-aws-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "eks",
                "clusterName": "neoflow-prod-mumbai-eks-cluster",
                "vpcId": "vpc-neoflow-aws-mumbai",
                "resourceSubtype": "eks_service",
                "namespace": "neoflow",
                "replicas": 2,
                "readyReplicas": 2,
                "availableReplicas": 2,
                "aws_status": "running",
                "containers": [
                    {
                        "name": "payment-gateway",
                        "image": "123456789012.dkr.ecr.ap-south-1.amazonaws.com/payment-gateway:v2.4.1",
                    },
                ],
            },
        },
        {
            "id": "neoflow-prod-eks-cluster/transaction-processor-service",
            "name": "transaction-processor-service",
            "resourceType": "service",
            "status": "online",
            "statusText": "2/2 running",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": [
                "subnet-neoflow-aws-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "eks",
                "clusterName": "neoflow-prod-mumbai-eks-cluster",
                "vpcId": "vpc-neoflow-aws-mumbai",
                "resourceSubtype": "eks_service",
                "namespace": "neoflow",
                "replicas": 2,
                "readyReplicas": 2,
                "availableReplicas": 2,
                "aws_status": "running",
                "containers": [
                    {
                        "name": "transaction-processor",
                        "image": "123456789012.dkr.ecr.ap-south-1.amazonaws.com/transaction-processor:v1.9.0",
                    },
                ],
            },
        },
        {
            "id": "neoflow-prod-eks-cluster/kyc-verification-service",
            "name": "kyc-verification-service",
            "resourceType": "service",
            "status": "online",
            "statusText": "1/1 running",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": [
                "subnet-neoflow-aws-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "eks",
                "clusterName": "neoflow-prod-mumbai-eks-cluster",
                "vpcId": "vpc-neoflow-aws-mumbai",
                "resourceSubtype": "eks_service",
                "namespace": "neoflow",
                "replicas": 1,
                "readyReplicas": 1,
                "availableReplicas": 1,
                "aws_status": "running",
                "containers": [
                    {
                        "name": "kyc-verification",
                        "image": "123456789012.dkr.ecr.ap-south-1.amazonaws.com/kyc-verification:v3.1.2",
                    },
                ],
            },
        },
        {
            "id": "i-0mumbai001neoflow",
            "name": "ip-10-20-1-101.ap-south-1.compute.internal",
            "resourceType": "service",
            "status": "online",
            "statusText": "Running",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": [
                "subnet-neoflow-aws-app-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "eks",
                "clusterName": "neoflow-prod-mumbai-eks-cluster",
                "resourceSubtype": "ec2",
                "aws_status": "running",
                "instanceId": "i-0mumbai001neoflow",
                "nodeGroupName": "ng-neoflow-app",
                "vpcId": "vpc-neoflow-aws-mumbai",
            },
        },
        {
            "id": "eks-ds-neoflow-prod-mumbai-eks-cluster-neoflow-audit-agent",
            "name": "neoflow-audit-agent",
            "resourceType": "service",
            "status": "online",
            "statusText": "3/3 ready",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "eks",
                "clusterName": "neoflow-prod-mumbai-eks-cluster",
                "vpcId": "vpc-neoflow-aws-mumbai",
                "resourceSubtype": "eks_daemonset",
                "namespace": "neoflow-system",
                "desiredNumberScheduled": 3,
                "numberReady": 3,
                "containers": [
                    {
                        "name": "neoflow-audit-agent",
                        "image": "123456789012.dkr.ecr.ap-south-1.amazonaws.com/audit-agent:v1.2.0",
                    },
                ],
            },
        },
        {
            "id": "eks-ds-neoflow-prod-mumbai-eks-cluster-neoflow-secrets-agent",
            "name": "neoflow-secrets-agent",
            "resourceType": "service",
            "status": "online",
            "statusText": "3/3 ready",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "clusterType": "eks",
                "clusterName": "neoflow-prod-mumbai-eks-cluster",
                "vpcId": "vpc-neoflow-aws-mumbai",
                "resourceSubtype": "eks_daemonset",
                "namespace": "neoflow-system",
                "desiredNumberScheduled": 3,
                "numberReady": 3,
                "containers": [
                    {
                        "name": "neoflow-secrets-agent",
                        "image": "123456789012.dkr.ecr.ap-south-1.amazonaws.com/secrets-agent:v2.0.1",
                    },
                ],
            },
        },
        {
            "id": "aws-mumbai/ledger-db",
            "name": "ledger-db",
            "resourceType": "database",
            "status": "online",
            "statusText": "Available",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": [
                "subnet-neoflow-aws-data-1a",
            ],
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {
                "databaseType": "aurora-postgresql",
                "aws_status": "available",
            },
        },
        {
            "id": "arn:aws:s3:::neoflow-compliance-reports-store",
            "name": "compliance-reports-store",
            "resourceType": "bucket",
            "status": "online",
            "statusText": "Online",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {},
        },
        {
            "id": "arn:aws:sqs:ap-south-1:123456789012:payment-events-queue.fifo",
            "name": "payment-events-queue.fifo",
            "resourceType": "queue",
            "status": "online",
            "statusText": "Online",
            "vendor": "AWS",
            "cloudRegion": "ap-south-1",
            "cloudRegionId": "cr-aws-ap-south-1-neoflow",
            "subnetIds": None,
            "position": {
                "x": 0,
                "y": 0,
            },
            "settings": {},
        },
    ],
    "nodeVariables": {},
    "variableRefs": {
        "gcp-dubai/payment-gateway-service": [
            {"dbId": 2001, "name": "DB_URL", "refVariableId": 1001},
            {"dbId": 2002, "name": "PAYMENT_QUEUE_TOPIC", "refVariableId": 1002},
        ],
        "gcp-dubai/kyc-verification-service": [
            {"dbId": 2003, "name": "COMPLIANCE_BUCKET", "refVariableId": 1003},
        ],
        "neoflow-prod-eks-cluster/payment-gateway-service": [
            {"dbId": 2004, "name": "DB_URL", "refVariableId": 1004},
            {"dbId": 2005, "name": "PAYMENT_QUEUE_URL", "refVariableId": 1005},
        ],
        "neoflow-prod-eks-cluster/kyc-verification-service": [
            {"dbId": 2006, "name": "COMPLIANCE_BUCKET", "refVariableId": 1006},
        ],
    },
    "securityGroupRules": [
        {
            "id": "sg-gcp-pgw-txn",
            "sourceNodeId": "gcp-dubai/payment-gateway-service",
            "targetNodeId": "gcp-dubai/transaction-processor-service",
            "direction": "egress",
            "protocol": "gRPC",
            "port": 50051,
            "description": "Payment gateway calls transaction processor",
        },
        {
            "id": "sg-aws-pgw-txn",
            "sourceNodeId": "neoflow-prod-eks-cluster/payment-gateway-service",
            "targetNodeId": "neoflow-prod-eks-cluster/transaction-processor-service",
            "direction": "egress",
            "protocol": "gRPC",
            "port": 50051,
            "description": "Payment gateway calls transaction processor",
        },
    ],
}
