"""Initial baseline - existing schema

Revision ID: 6b1adf98577d
Revises: 
Create Date: 2025-11-04 18:04:34.822954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b1adf98577d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_mst',
    sa.Column('infra_provider_enum', sa.Enum('on_prem', 'aws', 'gcp', 'azure', name='infra_provider_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('chat_info',
    sa.Column('tenants_mst_code', sa.String(length=100), nullable=False),
    sa.Column('applications_mst_code', sa.String(length=100), nullable=False),
    sa.Column('resource_group_mst_code', sa.String(length=100), nullable=False),
    sa.Column('services_mst_code', sa.String(length=100), nullable=True),
    sa.Column('environment_enum', sa.Enum('dev', 'staging', 'prod', name='environment_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['applications_mst_code'], ['applications_mst.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_group_mst_code'], ['resource_group_mst.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['services_mst_code'], ['services_mst.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenants_mst_code'], ['tenants_mst.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_index('idx_aws_secrets_parameters_active', table_name='aws_secrets_parameters_mst')
    op.drop_index('idx_aws_secrets_parameters_arn', table_name='aws_secrets_parameters_mst', postgresql_where='(resource_arn IS NOT NULL)')
    op.drop_index('idx_aws_secrets_parameters_composite', table_name='aws_secrets_parameters_mst')
    op.drop_index('idx_aws_secrets_parameters_env', table_name='aws_secrets_parameters_mst')
    op.drop_index('idx_aws_secrets_parameters_path', table_name='aws_secrets_parameters_mst')
    op.drop_index('idx_aws_secrets_parameters_service', table_name='aws_secrets_parameters_mst')
    op.drop_index('idx_aws_secrets_parameters_tenant', table_name='aws_secrets_parameters_mst')
    op.drop_index('idx_aws_secrets_parameters_type', table_name='aws_secrets_parameters_mst')
    op.drop_table('aws_secrets_parameters_mst')
    op.drop_table('datadog_alert_query_ref')
    op.alter_column('monitoring_policy_overrides_mst', 'tenants_mst_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Tenant scope - if set, override applies to this tenant only. NULL = cross-tenant (global) override',
               existing_nullable=True)
    op.alter_column('monitoring_policy_overrides_mst', 'applications_mst_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Application scope - if set, override applies to this application. Typically used with tenants_mst_code',
               existing_nullable=True)
    op.alter_column('monitoring_policy_overrides_mst', 'resource_group_mst_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Resource group scope - MOST SPECIFIC service grouping level. Typically used with applications_mst_code and tenants_mst_code',
               existing_nullable=True)
    op.alter_column('monitoring_policy_overrides_mst', 'infrastructuretype_ref_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Infrastructure type filter (ec2, rds, vm, eks, etc.) - if set, override only applies to this infrastructure type',
               existing_nullable=True)
    op.alter_column('region_ref', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('region_ref', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('region_ref', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_region_ref_active', table_name='region_ref')
    op.drop_index('idx_region_ref_vendor', table_name='region_ref', postgresql_where='(is_active = true)')
    op.drop_table_comment(
        'region_ref',
        existing_comment='Reference data for cloud vendor regions. Used for FK validation and UI dropdowns.',
        schema=None
    )
    op.alter_column('services_mst', 'infra_vendor_enum',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('on_prem', 'aws', 'gcp', 'azure', name='infra_vendor_enum'),
               comment=None,
               existing_comment='Infrastructure vendor where service is deployed',
               existing_nullable=False,
               existing_server_default=sa.text("'aws'::character varying"))
    op.alter_column('services_mst', 'region_ref_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Foreign key to region_ref for predefined regions (cloud vendors)',
               existing_nullable=True)
    op.alter_column('services_mst', 'region_custom',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Custom region string for on-prem deployments only',
               existing_nullable=True)
    op.alter_column('services_mst', 'region_display',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Computed column: returns actual region (custom or ref code)',
               existing_nullable=True)
    op.drop_index('idx_services_mst_infrastructuretype_ref_code', table_name='services_mst')
    op.drop_index('idx_services_mst_region_custom', table_name='services_mst')
    op.drop_index('idx_services_mst_region_display', table_name='services_mst')
    op.drop_index('idx_services_mst_region_ref', table_name='services_mst')
    op.drop_index('idx_services_mst_vendor', table_name='services_mst')
    op.drop_index('idx_services_mst_vendor_region', table_name='services_mst')
    op.drop_index('idx_tenants_mst_subdomain', table_name='tenants_mst')
    op.alter_column('user_mst', 'auth_provider_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique identifier from the authentication provider',
               existing_nullable=True)
    op.alter_column('user_mst', 'auth_provider',
               existing_type=postgresql.ENUM('clerk', 'auth0', 'cognito', 'firebase', 'okta', 'manual', name='auth_provider_t'),
               comment=None,
               existing_comment='Authentication provider: clerk, auth0, cognito, firebase, okta, or manual',
               existing_nullable=True,
               existing_server_default=sa.text("'clerk'::auth_provider_t"))
    op.alter_column('user_mst', 'is_org_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Whether the user is the owner of their organization/tenant',
               existing_server_default=sa.text('false'))
    op.drop_index('idx_user_mst_auth_provider', table_name='user_mst')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_mst_auth_provider', 'user_mst', ['auth_provider'], unique=False)
    op.alter_column('user_mst', 'is_org_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Whether the user is the owner of their organization/tenant',
               existing_server_default=sa.text('false'))
    op.alter_column('user_mst', 'auth_provider',
               existing_type=postgresql.ENUM('clerk', 'auth0', 'cognito', 'firebase', 'okta', 'manual', name='auth_provider_t'),
               comment='Authentication provider: clerk, auth0, cognito, firebase, okta, or manual',
               existing_nullable=True,
               existing_server_default=sa.text("'clerk'::auth_provider_t"))
    op.alter_column('user_mst', 'auth_provider_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique identifier from the authentication provider',
               existing_nullable=True)
    op.create_index('idx_tenants_mst_subdomain', 'tenants_mst', ['subdomain'], unique=False)
    op.create_index('idx_services_mst_vendor_region', 'services_mst', ['infra_vendor_enum', 'region_ref_code'], unique=False)
    op.create_index('idx_services_mst_vendor', 'services_mst', ['infra_vendor_enum'], unique=False)
    op.create_index('idx_services_mst_region_ref', 'services_mst', ['region_ref_code'], unique=False)
    op.create_index('idx_services_mst_region_display', 'services_mst', ['region_display'], unique=False)
    op.create_index('idx_services_mst_region_custom', 'services_mst', ['region_custom'], unique=False)
    op.create_index('idx_services_mst_infrastructuretype_ref_code', 'services_mst', ['infrastructuretype_ref_code'], unique=False)
    op.alter_column('services_mst', 'region_display',
               existing_type=sa.VARCHAR(length=100),
               comment='Computed column: returns actual region (custom or ref code)',
               existing_nullable=True)
    op.alter_column('services_mst', 'region_custom',
               existing_type=sa.VARCHAR(length=100),
               comment='Custom region string for on-prem deployments only',
               existing_nullable=True)
    op.alter_column('services_mst', 'region_ref_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Foreign key to region_ref for predefined regions (cloud vendors)',
               existing_nullable=True)
    op.alter_column('services_mst', 'infra_vendor_enum',
               existing_type=sa.Enum('on_prem', 'aws', 'gcp', 'azure', name='infra_vendor_enum'),
               type_=sa.VARCHAR(length=50),
               comment='Infrastructure vendor where service is deployed',
               existing_nullable=False,
               existing_server_default=sa.text("'aws'::character varying"))
    op.create_table_comment(
        'region_ref',
        'Reference data for cloud vendor regions. Used for FK validation and UI dropdowns.',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_region_ref_vendor', 'region_ref', ['infra_vendor_enum'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_region_ref_active', 'region_ref', ['is_active', 'is_deleted'], unique=False)
    op.alter_column('region_ref', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('region_ref', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('region_ref', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('monitoring_policy_overrides_mst', 'infrastructuretype_ref_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Infrastructure type filter (ec2, rds, vm, eks, etc.) - if set, override only applies to this infrastructure type',
               existing_nullable=True)
    op.alter_column('monitoring_policy_overrides_mst', 'resource_group_mst_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Resource group scope - MOST SPECIFIC service grouping level. Typically used with applications_mst_code and tenants_mst_code',
               existing_nullable=True)
    op.alter_column('monitoring_policy_overrides_mst', 'applications_mst_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Application scope - if set, override applies to this application. Typically used with tenants_mst_code',
               existing_nullable=True)
    op.alter_column('monitoring_policy_overrides_mst', 'tenants_mst_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tenant scope - if set, override applies to this tenant only. NULL = cross-tenant (global) override',
               existing_nullable=True)
    op.create_table('datadog_alert_query_ref',
    sa.Column('infrastructuretype_ref_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('alerttype_ref_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('signal_kind', postgresql.ENUM('metric', 'log', 'trace', 'event', name='signal_kind_t'), autoincrement=False, nullable=False),
    sa.Column('query_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alerttype_ref_code'], ['alerttype_ref.code'], name='datadog_alert_query_ref_alerttype_ref_code_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['infrastructuretype_ref_code'], ['infrastructuretype_ref.code'], name='datadog_alert_query_ref_infrastructuretype_ref_code_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='datadog_alert_query_ref_pkey'),
    sa.UniqueConstraint('code', name='datadog_alert_query_ref_code_key'),
    sa.UniqueConstraint('infrastructuretype_ref_code', 'alerttype_ref_code', 'signal_kind', name='uq_infra_alert_signal')
    )
    op.create_table('aws_secrets_parameters_mst',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tenants_mst_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('services_mst_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', postgresql.ENUM('secret', 'parameter', name='aws_resource_type_enum'), autoincrement=False, nullable=False, comment='Type of AWS resource: secret (Secrets Manager) or parameter (SSM Parameter Store)'),
    sa.Column('full_resource_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='Full AWS resource path following pattern: tenant/env/region/service/name'),
    sa.Column('resource_arn', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='AWS ARN of the resource (populated after creation in AWS)'),
    sa.Column('environments_enum', postgresql.ENUM('dev', 'staging', 'prod', name='environment_enum'), autoincrement=False, nullable=False, comment='Environment: dev, staging, or prod'),
    sa.Column('is_secret_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='True if secret/parameter deleted in AWS but kept in DB for tracking'),
    sa.Column('parameter_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Parameter type for SSM: String, StringList, or SecureString. Null for Secrets Manager.'),
    sa.ForeignKeyConstraint(['services_mst_code'], ['services_mst.code'], name='fk_aws_secrets_parameters_service', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenants_mst_code'], ['tenants_mst.code'], name='fk_aws_secrets_parameters_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='aws_secrets_parameters_mst_pkey'),
    sa.UniqueConstraint('code', name='aws_secrets_parameters_mst_code_key'),
    comment='Stores references to AWS Secrets Manager secrets and SSM Parameter Store parameters.\nPath naming convention: {tenant}/{environment}/{region}/{service_name}/{secret_name}'
    )
    op.create_index('idx_aws_secrets_parameters_type', 'aws_secrets_parameters_mst', ['resource_type'], unique=False)
    op.create_index('idx_aws_secrets_parameters_tenant', 'aws_secrets_parameters_mst', ['tenants_mst_code'], unique=False)
    op.create_index('idx_aws_secrets_parameters_service', 'aws_secrets_parameters_mst', ['services_mst_code'], unique=False)
    op.create_index('idx_aws_secrets_parameters_path', 'aws_secrets_parameters_mst', ['full_resource_path'], unique=False)
    op.create_index('idx_aws_secrets_parameters_env', 'aws_secrets_parameters_mst', ['environments_enum'], unique=False)
    op.create_index('idx_aws_secrets_parameters_composite', 'aws_secrets_parameters_mst', ['tenants_mst_code', 'services_mst_code', 'resource_type', 'environments_enum'], unique=False)
    op.create_index('idx_aws_secrets_parameters_arn', 'aws_secrets_parameters_mst', ['resource_arn'], unique=False, postgresql_where='(resource_arn IS NOT NULL)')
    op.create_index('idx_aws_secrets_parameters_active', 'aws_secrets_parameters_mst', ['is_active', 'is_deleted', 'is_secret_deleted'], unique=False)
    op.drop_table('chat_info')
    op.drop_table('region_mst')
    # ### end Alembic commands ###
