apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: vllm-runtime
spec:
  annotations:
    prometheus.kserve.io/port: "8000"
    prometheus.kserve.io/path: /metrics
  supportedModelFormats:
    - name: pytorch
      version: "1"
      autoSelect: true
  protocolVersions:
    - v2
    - grpc-v2
  containers:
    - name: kserve-container
      image: vllm/vllm-openai:latest
      command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
      ports:
        - containerPort: 8000
          protocol: TCP
      env:
        - name: HF_HOME
          value: /mnt/models/.cache
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "1"
          memory: 2Gi
