"""
Default EKS Jenkins Pipeline Generator Component

Generates a language-agnostic Jenkinsfile pipeline script (Groovy) in-memory
from templates/generic/Jenkinsfile-eks-regular by pure value substitution.
The generated script is NOT committed to any repository — it is injected
into a Jenkins Pipeline job config via the Jenkins REST API.

Handles REGULAR services only (docker build + ECR push). MODEL_SERVING
deploys are generated by DefaultModelServingJenkinsGenComponent against
templates/generic/Jenkinsfile-eks-modelserving.

K8s manifests are committed to the infra repo by DefaultEksDeployScriptGenComponent
and fetched at Jenkins runtime by git-cloning the infra repo (strongly
consistent — avoids the stale-404 window of raw.githubusercontent.com).
"""

import logging
import os
import re
from typing import Dict, Any

import aiofiles

from app.infra_chat_agent_with_tools.mcp_server.eks.eks_config import (
    DEFAULT_EKS_CLUSTER_NAME,
    DEFAULT_AWS_REGION,
    AWS_ACCOUNT_ID as DEFAULT_AWS_ACCOUNT_ID,
)
from app.core.config import settings

logger = logging.getLogger(__name__)


_GENERIC_TEMPLATE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "templates", "generic", "Jenkinsfile-eks-regular"
)




def _derive_name_prefix(tenant_code: str, geo_loc_mst_code: str = "") -> str:
    """Build the k8s name prefix: {tenant}-{env}-{region_name}-{index}.

    Uses tenant code, onboarding defaults for env/index, and extracts
    the region name from geo_loc_mst_code (e.g. "region-aslam-mumbai" → "mumbai").
    """
    if not tenant_code:
        return ""
    env = settings.onboarding_default_env
    index = settings.onboarding_default_index
    region_name = ""
    if geo_loc_mst_code:
        parts = geo_loc_mst_code.rsplit("-", 1)
        if len(parts) > 1:
            region_name = parts[-1]
    if not region_name:
        region_name = settings.onboarding_default_region_code
    return f"{tenant_code}-{env}-{region_name}-{index}"


async def _fetch_infra_values(db, infrastructure_mst_code: str, tenant_code: str = "", geo_loc_mst_code: str = "") -> Dict[str, Any]:
    """Fetch EKS cluster metadata from infrastructure_mst."""
    if not infrastructure_mst_code or not db:
        return {"name_prefix": _derive_name_prefix(tenant_code, geo_loc_mst_code)}
    from app.repository.infrastructure_mst_repository import InfrastructureMstRepository
    infra_repo = InfrastructureMstRepository(db)
    infrastructure = await infra_repo.get_by_code(infrastructure_mst_code)
    if not infrastructure:
        return {"name_prefix": _derive_name_prefix(tenant_code, geo_loc_mst_code)}

    locator = infrastructure.locator or {}
    vendor_auth = (infrastructure.infra_vendor_account.auth_config or {}) if infrastructure.infra_vendor_account else {}
    cluster_name = locator.get("cluster_name") or locator.get("cluster") or infrastructure.name

    return {
        "cluster_name": cluster_name,
        "aws_region": locator.get("region") or vendor_auth.get("region", DEFAULT_AWS_REGION),
        "account_id": vendor_auth.get("account_id", DEFAULT_AWS_ACCOUNT_ID),
        "subdomain": infrastructure.tenants_mst_code or "",
        "name_prefix": _derive_name_prefix(tenant_code, geo_loc_mst_code),
    }


class DefaultEksJenkinsGenComponent:
    """Generates Jenkinsfile content from templates for Jenkins pipeline jobs."""

    def __init__(self):
        self.logger = logging.getLogger(__name__)

    async def generate_jenkinsfile(
        self,
        config_snapshot: Dict[str, Any],
        db=None,
        tenant_code: str = "",
    ) -> str:
        """
        Generate a Jenkinsfile pipeline script from the appropriate language template.

        Args:
            config_snapshot: Service configuration dict containing:
                - service_name, language/language_name, language_version/version
                - environment, infrastructure_mst_code
                - dockerfile_path, build_args
            db: Async database session for fetching infrastructure values.
            tenant_code: Tenant code (kept for API compatibility, naming is
                derived from infrastructure_mst locator).

        Returns:
            Generated Jenkinsfile content string (Groovy pipeline script).
        """
        service_name = config_snapshot.get("service_name", "")
        if service_name.lower().endswith("-service"):
            service_name = service_name[:-8]

        environment = config_snapshot.get("environment") or "stage"
        dockerfile_path = config_snapshot.get("dockerfile_path") or "Dockerfile"

        # Fetch infrastructure values from DB
        infrastructure_mst_code = config_snapshot.get("infrastructure_mst_code", "")
        geo_loc_mst_code = config_snapshot.get("geo_loc_mst_code", "")
        infra_values = {}
        if db and infrastructure_mst_code:
            try:
                infra_values = await _fetch_infra_values(db, infrastructure_mst_code, tenant_code, geo_loc_mst_code)
            except Exception as exc:
                self.logger.warning("Failed to fetch infra values: %s", exc)
        if not infra_values.get("name_prefix"):
            infra_values["name_prefix"] = _derive_name_prefix(tenant_code, geo_loc_mst_code)

        # Derive K8s resource name using infra naming convention:
        # {org}-{env}-{region_code}-{index}-{service_name}-{suffix}
        # Lowercase service_name for AWS ECR and K8s namespace compatibility
        safe_name = re.sub(r"[^a-z0-9-]", "-", service_name.lower()).strip("-")
        name_prefix = infra_values.get("name_prefix", "")
        if name_prefix:
            k8s_name = f"{name_prefix}-{safe_name}"
        else:
            k8s_name = safe_name
        namespace = f"{tenant_code}-ns"

        cluster_name = (
            config_snapshot.get("eks_cluster_name")
            or infra_values.get("cluster_name", DEFAULT_EKS_CLUSTER_NAME)
        )
        aws_region = config_snapshot.get("aws_region") or infra_values.get("aws_region", DEFAULT_AWS_REGION)
        account_id = config_snapshot.get("aws_account_id") or infra_values.get("account_id", DEFAULT_AWS_ACCOUNT_ID)
        logger.info("[generate_jenkinsfile] account_id=%s (snapshot=%s, infra=%s, default=%s)", account_id, config_snapshot.get("aws_account_id"), infra_values.get("account_id"), DEFAULT_AWS_ACCOUNT_ID)
        ecr_registry = config_snapshot.get("ecr_registry") or f"{account_id}.dkr.ecr.{aws_region}.amazonaws.com"

        # Build args
        build_args = config_snapshot.get("build_args") or []
        custom_build_args = ""
        for arg in build_args:
            name = (arg.get("name") or arg.get("key") or "").strip()
            if name:
                custom_build_args += f"--build-arg {name}=${{{name}}} \\\n                        "

        # Load generic (language-agnostic) Jenkinsfile template
        async with aiofiles.open(_GENERIC_TEMPLATE_PATH, "r") as f:
            content = await f.read()

        # ── Resolve infra repo for manifest fetching at Jenkins runtime ──
        # Fresh session: `db` param may be None (this method is callable from
        # contexts that don't pass one) and we don't want a read-only tenant
        # lookup entangled with the caller's transaction.
        from app.utils.tenant_config import get_tenant_config
        from app.db.session import AsyncSessionLocal
        async with AsyncSessionLocal() as _db:
            tenant_cfg = await get_tenant_config(tenant_code, _db)
        infra_repo = tenant_cfg.github_infra_repository
        infra_branch = tenant_cfg.github_infra_branch or "main"
        manifests_path = f"eks-services/{safe_name}/deployment"

        content = content.replace("{{INFRA_REPO}}", infra_repo)
        content = content.replace("{{INFRA_BRANCH}}", infra_branch)
        content = content.replace("{{MANIFESTS_PATH}}", manifests_path)

        # Replace placeholders — both SERVICE_NAME and ECR_REPO_NAME use the
        # subdomain-prefixed name for consistent resource naming.
        content = content.replace("{{SERVICE_NAME}}", k8s_name)
        content = content.replace("{{ECR_REPO_NAME}}", k8s_name)
        content = content.replace("{{ENVIRONMENT}}", environment)
        content = content.replace("{{AWS_REGION}}", aws_region)
        content = content.replace("{{ECR_REGISTRY}}", ecr_registry)
        content = content.replace("{{EKS_CLUSTER_NAME}}", cluster_name)
        content = content.replace("{{NAMESPACE}}", namespace)
        content = content.replace("{{DOCKERFILE_PATH}}", dockerfile_path)
        content = content.replace("{{CUSTOM_BUILD_ARGS}}", custom_build_args)

        # Git checkout — source repo token is injected via SOURCE_GITHUB_TOKEN param.
        repo_raw = config_snapshot.get("repository") or ""
        owner_repo = repo_raw
        if owner_repo.startswith("https://github.com/"):
            owner_repo = owner_repo[len("https://github.com/"):]
        if owner_repo.startswith("http://github.com/"):
            owner_repo = owner_repo[len("http://github.com/"):]
        owner_repo = owner_repo.rstrip("/").removesuffix(".git")

        repo_branch = config_snapshot.get("branches") or "main"
        if isinstance(repo_branch, list):
            repo_branch = repo_branch[0] if repo_branch else "main"

        content = content.replace("{{OWNER_REPO}}", owner_repo)
        content = content.replace("{{REPO_BRANCH}}", repo_branch)

        # Webhook callback for build status + ALB URL
        webhook_url = f"{settings.devlift_backend_url}/api/v1/webhooks/jenkins-webhook"
        content = content.replace("{{OBSTOOL_WEBHOOK_URL}}", webhook_url)
        content = content.replace("{{WEBHOOK_SECRET}}", settings.pipeline_webhook_secret or "")

        return content

    async def generate(
        self,
        tenant: str,
        repository,
        file_location,
        queue_dict: dict,
        workflow_context,
        upload_to_s3: bool = False,
        db=None,
    ) -> str:
        """
        Script gen interface wrapper — generates Jenkinsfile and stages with mode="jenkins".
        Called by ScriptGenHandler in the main workflow loop.
        """
        config_snapshot = queue_dict.get("config_snapshot") or {}
        tenant_code = queue_dict.get("tenant_code") or tenant

        content = await self.generate_jenkinsfile(
            config_snapshot=config_snapshot,
            db=db,
            tenant_code=tenant_code,
        )

        service_name = config_snapshot.get("service_name") or config_snapshot.get("name", "unknown")
        if service_name.lower().endswith("-service"):
            service_name = service_name[:-8]

        # Stage for inline Jenkins deploy (mode="jenkins") + git commit to infra repo
        if workflow_context:
            workflow_context.staged_files.append({
                "repo": file_location.repo or "",
                "base_branch": file_location.base_branch or "",
                "feature_branch": file_location.feature_branch or "",
                "file_path": file_location.file_path or "",
                "content": content,
                "queue_id": queue_dict.get("id"),
                "script_gen_key": file_location.script_gen_key,
                "mode": "jenkins",
                "config_snapshot": config_snapshot,
                "job_name": service_name,
            })

            # Append commit message for infra repo git commit
            if file_location.repo and file_location.file_path:
                key = f"{file_location.repo}|||{file_location.base_branch or ''}"
                queue_label = queue_dict.get("code") or queue_dict.get("id")
                msg = f"{queue_label}: add Jenkinsfile for {service_name}"
                existing = workflow_context.commit_messages.get(key, "")
                workflow_context.commit_messages[key] = f"{existing}\n{msg}" if existing else msg
            if queue_dict.get("id"):
                workflow_context.script_gen_responses[queue_dict["id"]][file_location.script_gen_key] = {
                    "original_content": content,
                    "preview_content": content,
                }

        return content
