"""
EKS deployment status monitoring functions.

Provides tools to:
1. Get ALB URL for deployed services
2. Monitor GitHub Actions deployment status
"""
import subprocess
import asyncio
import logging
from typing import Dict, Optional
from datetime import datetime

from app.infra_chat_agent_with_tools.mcp_server.eks.eks_config import (
    KUBECTL_GET_TIMEOUT,
    ALLOWED_GITHUB_ORGS,
    DEPLOYMENT_POLL_INTERVAL,
    DEPLOYMENT_MAX_DURATION,
    DEFAULT_EKS_CLUSTER_NAME,
    DEFAULT_AWS_REGION
)
from app.infra_chat_agent_with_tools.mcp_server.eks.eks_generators import sanitize_name
from app.integrations.github_integration import GitHubIntegration
from app.core.config import settings
from app.utils.github_app_token import get_token_for_org
from app.db.session import AsyncSessionLocal

logger = logging.getLogger(__name__)


def ensure_kubectl_configured() -> bool:
    """
    Ensure kubectl is configured for the EKS cluster.
    Runs aws eks update-kubeconfig if kubectl is not configured.

    Returns:
        True if kubectl is configured successfully, False otherwise
    """
    try:
        # First check which AWS identity is being used
        identity_result = subprocess.run(
            ["aws", "sts", "get-caller-identity"],
            capture_output=True,
            text=True,
            timeout=10
        )

        if identity_result.returncode == 0:
            logger.info(f"AWS Identity being used: {identity_result.stdout.strip()}")
        else:
            logger.warning(f"Could not determine AWS identity: {identity_result.stderr}")

        # Check if kubectl can access the cluster
        result = subprocess.run(
            ["kubectl", "cluster-info"],
            capture_output=True,
            text=True,
            timeout=5
        )

        if result.returncode == 0:
            logger.info("kubectl is already configured and working")
            return True

        # kubectl not configured, configure it now
        logger.info(f"kubectl not configured. Configuring for cluster: {DEFAULT_EKS_CLUSTER_NAME} in region: {DEFAULT_AWS_REGION}")
        config_result = subprocess.run(
            ["aws", "eks", "update-kubeconfig",
             "--name", DEFAULT_EKS_CLUSTER_NAME,
             "--region", DEFAULT_AWS_REGION],
            capture_output=True,
            text=True,
            timeout=30
        )

        if config_result.returncode == 0:
            logger.info(f"kubectl configured successfully. Output: {config_result.stdout.strip()}")
            # Verify it works
            verify_result = subprocess.run(
                ["kubectl", "cluster-info"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if verify_result.returncode == 0:
                logger.info("kubectl verification successful")
                return True
            else:
                logger.error(f"kubectl configuration succeeded but verification failed: {verify_result.stderr}")
                return False
        else:
            logger.error(f"Failed to configure kubectl. Error: {config_result.stderr}")
            return False

    except subprocess.TimeoutExpired as e:
        logger.error(f"Timeout while configuring kubectl: {str(e)}")
        return False
    except Exception as e:
        logger.error(f"Unexpected error configuring kubectl: {str(e)}", exc_info=True)
        return False


def validate_github_org(github_repo: str):
    """
    Validate that the GitHub organization is in the allowed list.

    Args:
        github_repo: Repository in format "owner/repo"

    Raises:
        Exception: If organization is not allowed
    """
    if "/" not in github_repo:
        raise Exception(f"Invalid GitHub repository format: {github_repo}. Expected format: 'owner/repo'")

    owner = github_repo.split("/")[0]
    if owner not in ALLOWED_GITHUB_ORGS:
        raise Exception(
            f"GitHub organization '{owner}' is not in the allowed list. "
            f"Allowed organizations: {', '.join(ALLOWED_GITHUB_ORGS)}"
        )
    logger.info(f"GitHub org validation passed for: {owner}")


def get_workflow_filename(service_name: str, environment: str) -> str:
    """
    Generate the expected GitHub Actions workflow filename.

    The workflow file is generated by the EKS onboarding tool with the pattern:
    .github/workflows/deploy-{service_name}-{environment}.yml

    Args:
        service_name: Service name (will be sanitized)
        environment: Deployment environment (dev, stage, qa, prod)

    Returns:
        Workflow filename (e.g., "deploy-api-service-stage.yml")
    """
    sanitized_name = sanitize_name(service_name)
    filename = f"deploy-{sanitized_name}-{environment}.yml"
    logger.info(f"Generated workflow filename: {filename}")
    return filename


def get_alb_url_for_service(
    service_name: str,
    namespace: Optional[str] = None
) -> Dict:
    """
    Get the ALB URL for a deployed service by querying the Kubernetes ingress.

    Args:
        service_name: Name of the service
        namespace: Kubernetes namespace (defaults to service_name if not provided)

    Returns:
        Dict with:
        - alb_url: ALB URL if available
        - status: "ready", "pending", or "not_found"
        - message: Descriptive message
    """
    # Ensure kubectl is configured for EKS
    if not ensure_kubectl_configured():
        return {
            "alb_url": None,
            "status": "error",
            "message": "kubectl is not configured for EKS cluster. Please run: aws eks update-kubeconfig --name devlift-dev-cluster --region ap-south-1",
            "namespace": namespace or sanitize_name(service_name)
        }

    # Default namespace to service name
    if namespace is None:
        namespace = sanitize_name(service_name)

    ingress_name = f"{service_name}-ingress"

    try:
        # Query kubectl for ingress ALB hostname
        result = subprocess.run(
            [
                "kubectl", "get", "ingress",
                ingress_name,
                "-n", namespace,
                "-o", "jsonpath={.status.loadBalancer.ingress[0].hostname}"
            ],
            capture_output=True,
            text=True,
            timeout=KUBECTL_GET_TIMEOUT
        )

        if result.returncode != 0:
            # Ingress not found
            if "not found" in result.stderr.lower():
                return {
                    "alb_url": None,
                    "status": "not_found",
                    "message": f"Ingress '{ingress_name}' not found in namespace '{namespace}'. Service may not be deployed yet.",
                    "ingress_name": ingress_name,
                    "namespace": namespace
                }
            else:
                return {
                    "alb_url": None,
                    "status": "error",
                    "message": f"Failed to query ingress: {result.stderr}",
                    "ingress_name": ingress_name,
                    "namespace": namespace
                }

        alb_hostname = result.stdout.strip()

        if alb_hostname:
            alb_url = f"http://{alb_hostname}"
            return {
                "alb_url": alb_url,
                "status": "ready",
                "message": f"ALB is provisioned and ready at {alb_url}",
                "ingress_name": ingress_name,
                "namespace": namespace
            }
        else:
            return {
                "alb_url": None,
                "status": "pending",
                "message": f"Ingress exists but ALB is still being provisioned. This typically takes 2-3 minutes.",
                "ingress_name": ingress_name,
                "namespace": namespace
            }

    except subprocess.TimeoutExpired:
        return {
            "alb_url": None,
            "status": "error",
            "message": f"kubectl command timed out after {KUBECTL_GET_TIMEOUT} seconds",
            "ingress_name": ingress_name,
            "namespace": namespace
        }
    except FileNotFoundError:
        return {
            "alb_url": None,
            "status": "error",
            "message": "kubectl is not installed or not in PATH. This functionality requires kubectl to be configured for EKS access. When running in ECS, ensure Dockerfile.ecs is used.",
            "ingress_name": ingress_name,
            "namespace": namespace
        }
    except Exception as e:
        return {
            "alb_url": None,
            "status": "error",
            "message": f"Error querying ingress: {str(e)}",
            "ingress_name": ingress_name,
            "namespace": namespace
        }


async def monitor_github_deployment_status(
    service_name: str,
    github_repo: str,
    branch: str,
    environment: str,
    poll_interval: int = DEPLOYMENT_POLL_INTERVAL,
    max_duration: int = DEPLOYMENT_MAX_DURATION
) -> Dict:
    """
    Check GitHub Actions deployment status once and return immediately.

    This function:
    1. Validates the GitHub organization
    2. Infers the workflow filename from service name and environment
    3. Gets the latest workflow run for the branch
    4. Returns the current status immediately

    The LLM should call this tool repeatedly until status is 'success', 'failure', or timeout.

    Args:
        service_name: Name of the service being deployed
        github_repo: GitHub repository in format "owner/repo"
        branch: Git branch to monitor (e.g., "main")
        environment: Deployment environment (dev, stage, qa, prod)
        poll_interval: Recommended seconds to wait before checking again (default: 10)
        max_duration: Maximum total time to keep checking in seconds (default: 600)

    Returns:
        Dict with:
        - status: "success", "failure", "in_progress", "not_found", or "error"
        - run_url: URL to the GitHub Actions run (if found)
        - run_id: GitHub Actions run ID (if found)
        - workflow_name: Name of the workflow (if found)
        - conclusion: GitHub workflow conclusion (if completed)
        - message: Descriptive message
        - next_action: Instructions for LLM on what to do next
        - wait_seconds: Recommended wait time before next check
    """
    try:
        # Step 1: Validate GitHub organization
        validate_github_org(github_repo)

        # Step 2: Parse owner and repo
        owner, repo = github_repo.split("/")

        # Step 3: Generate workflow filename
        workflow_file = get_workflow_filename(service_name, environment)

        # Step 4: Get GitHub token via GitHub App installation
        async with AsyncSessionLocal() as db:
            github_token = await get_token_for_org(owner, db)
        github_base_url = settings.github_base_url

        # Step 5: Get the latest workflow run
        logger.info(f"Fetching latest workflow run for {owner}/{repo}/{workflow_file} on branch {branch}")

        workflow_run = await GitHubIntegration.get_latest_workflow_run(
            token=github_token,
            base_url=github_base_url,
            owner=owner,
            repo=repo,
            workflow_file=workflow_file,
            branch=branch
        )

        if not workflow_run:
            # Try without filtering by event (get any recent run on the branch)
            logger.info(f"No workflow_dispatch run found, trying to get any recent run on {branch}")
            workflow_run = await _get_latest_workflow_run_any_event(
                github_token, github_base_url, owner, repo, workflow_file, branch
            )

        if not workflow_run:
            return {
                "status": "not_found",
                "run_url": None,
                "run_id": None,
                "workflow_name": workflow_file,
                "conclusion": None,
                "message": f"No recent workflow run found for {workflow_file} on branch {branch}. "
                          f"Make sure the workflow file exists and has been triggered.",
                "next_action": "stop",
                "wait_seconds": None
            }

        run_id = workflow_run["run_id"]
        run_url = workflow_run["run_url"]
        current_status = workflow_run["status"]
        workflow_name = workflow_run["workflow_name"]
        conclusion = workflow_run.get("conclusion")

        logger.info(f"Found workflow run {run_id}: {current_status} (conclusion: {conclusion}) - {run_url}")

        # Step 6: Check if completed
        if current_status == "completed":
            final_status = _map_github_conclusion(conclusion)

            return {
                "status": final_status,
                "run_url": run_url,
                "run_id": run_id,
                "workflow_name": workflow_name,
                "conclusion": conclusion,
                "message": f"✅ Workflow completed with status: {conclusion}. Run URL: {run_url}",
                "next_action": "stop",
                "wait_seconds": None
            }

        # Step 7: Return in-progress status with instructions to poll again
        return {
            "status": "in_progress",
            "run_url": run_url,
            "run_id": run_id,
            "workflow_name": workflow_name,
            "conclusion": None,
            "message": f"⏳ Workflow is currently running. Current status: {current_status}. Run URL: {run_url}",
            "next_action": "wait_and_retry",
            "wait_seconds": poll_interval,
            "max_duration": max_duration
        }

    except Exception as e:
        logger.error(f"Error checking deployment status: {str(e)}")
        return {
            "status": "error",
            "run_url": None,
            "run_id": None,
            "workflow_name": None,
            "conclusion": None,
            "message": f"❌ Error: {str(e)}",
            "next_action": "stop",
            "wait_seconds": None
        }


async def _get_latest_workflow_run_any_event(
    token: str,
    base_url: str,
    owner: str,
    repo: str,
    workflow_file: str,
    branch: str
) -> Optional[Dict]:
    """
    Get latest workflow run without filtering by event type.

    Fallback when no workflow_dispatch runs are found.
    """
    try:
        import httpx

        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "RegObs-App",
            "X-GitHub-Api-Version": "2022-11-28"
        }

        if "/" in workflow_file:
            workflow_file = workflow_file.split("/")[-1]

        url = f"{base_url}/repos/{owner}/{repo}/actions/workflows/{workflow_file}/runs"
        params = {
            "per_page": 1,
            "branch": branch
        }

        async with httpx.AsyncClient(timeout=300.0) as client:
            response = await client.get(url, headers=headers, params=params)

        if response.status_code != 200:
            return None

        data = response.json()
        workflow_runs = data.get("workflow_runs", [])

        if not workflow_runs:
            return None

        run = workflow_runs[0]
        return {
            "run_id": str(run["id"]),
            "run_url": run["html_url"],
            "status": run["status"],
            "conclusion": run.get("conclusion"),
            "workflow_name": run["name"],
            "head_sha": run.get("head_sha"),
            "created_at": run.get("created_at"),
            "updated_at": run.get("updated_at")
        }
    except Exception as e:
        logger.error(f"Error getting workflow run: {str(e)}")
        return None


def _map_github_conclusion(conclusion: Optional[str]) -> str:
    """
    Map GitHub workflow conclusion to user-friendly status.

    Args:
        conclusion: GitHub workflow conclusion (success, failure, cancelled, etc.)

    Returns:
        User-friendly status: "success", "failure", or "cancelled"
    """
    if conclusion == "success":
        return "success"
    elif conclusion in ["failure", "timed_out", "action_required"]:
        return "failure"
    elif conclusion in ["cancelled", "skipped"]:
        return "cancelled"
    else:
        return "unknown"


def _format_duration(start_time: datetime) -> str:
    """
    Format duration from start time to now.

    Args:
        start_time: Start datetime

    Returns:
        Formatted duration string (e.g., "2m 30s")
    """
    elapsed_seconds = int((datetime.now() - start_time).total_seconds())
    minutes = elapsed_seconds // 60
    seconds = elapsed_seconds % 60

    if minutes > 0:
        return f"{minutes}m {seconds}s"
    else:
        return f"{seconds}s"


async def trigger_github_workflow(
    service_name: str,
    github_repo: str,
    branch: str = "main",
    environment: str = "stage"
) -> Dict:
    """
    Trigger a GitHub Actions workflow to rebuild and redeploy a service.

    Args:
        service_name: Name of the service to rebuild
        github_repo: Repository in format "owner/repo"
        branch: Git branch to trigger on
        environment: Deployment environment

    Returns:
        Dict with status, message, and workflow details
    """
    # Validate GitHub organization
    try:
        validate_github_org(github_repo)
    except Exception as e:
        return {
            "status": "error",
            "message": str(e),
            "service_name": service_name,
            "github_repo": github_repo
        }

    # Get workflow filename
    workflow_filename = get_workflow_filename(service_name, environment)

    try:
        # Trigger workflow dispatch
        logger.info(f"Triggering workflow: {workflow_filename} on {github_repo}:{branch}")

        # GitHub API: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
        owner, repo = github_repo.split("/")

        async with AsyncSessionLocal() as db:
            github_token = await get_token_for_org(owner, db)

        result = await GitHubIntegration.trigger_workflow_dispatch(
            token=github_token,
            base_url=settings.github_base_url,
            owner=owner,
            repo=repo,
            workflow_file=workflow_filename,
            ref=branch
        )

        if result.get("success"):
            return {
                "status": "success",
                "message": f"Successfully triggered deployment workflow for {service_name}",
                "service_name": service_name,
                "github_repo": github_repo,
                "branch": branch,
                "environment": environment,
                "workflow_filename": workflow_filename,
                "workflow_url": f"https://github.com/{github_repo}/actions/workflows/{workflow_filename}"
            }
        else:
            return {
                "status": "error",
                "message": f"Failed to trigger workflow: {result.get('error', 'Unknown error')}",
                "service_name": service_name,
                "github_repo": github_repo
            }

    except Exception as e:
        logger.error(f"Error triggering workflow: {str(e)}", exc_info=True)
        return {
            "status": "error",
            "message": f"Error triggering workflow: {str(e)}",
            "service_name": service_name,
            "github_repo": github_repo
        }
